name: development

on:
  push:
    branches: 
      - development
    
jobs:
  build:
    runs-on : ubuntu-latest
      
    steps:
     -  name: checkout code
        uses: actions/checkout@v4
      
     - name: setup dotnet
       uses: actions/setup-dotnet@v4
       with:
          dotnet-version: 8.0.x
       
     - name: dotnet restore
       run : dotnet restore
       
     - name: dotnet clean
       run: dotnet clean 
     
     -  name: dotnet build
        run : dotnet build --configuration Debug
       
     - name: dotnet test
       run : dotnet test --verbosity normal 
       
      
      